### ISSUE TITLE
Live Web Server Sign Up Error

### ISSUE THREAD

**Issue by masoodbawa** [yTakkar/Instagram-clone#21]
Hi Faiyaz,

Thanks for the great work. 
I installed the package as instructed with all the correct details. 
The database connection works. No errors.
One problem though, signup.php does not post details to the database and complete the sign up process, unfortunately. 

Server details:
Shared hosting - cPanel
Php 5.6.30
MySQL 10.0.31 

Your help is very much appreciated. 
If you'd prefer, you could also mail me on oodieboy@gmail.com 

Thank you

**Comment by masoodbawa** [comment]
I will leave the site live for you to see and better understand. 

Please visit: http://primalprojects.co.za/mvp/ 

Thank you

**Comment by yTakkar** [comment]
Got the solution.

![snap 2017-08-23 at 14 15 50](https://user-images.githubusercontent.com/24929880/29607191-1a8f6468-880e-11e7-9cae-2c789b836f45.png)

Check the console, it is still sending xhr request to '/faiyaz/Instagram/..'.

**Solution:**

1. Make sure you have followed step no. 3.
2. If you have followed the above step, try changing the chrome browser, because sometimes chrome doesn't reload the files.

**Comment by masoodbawa** [comment]
How silly of me. Thanks buddy.

**Comment by yTakkar** [comment]
@masoodbawa welcome!!
