### ISSUE TITLE
My eyes were blinded by this terribly coded Instagram clone

### ISSUE THREAD

**Issue by webdeveloper73** [yTakkar/Instagram-clone#61]
This Instagram clone shows everything not to do when coding in PHP. For a clone like this an MVC framework should of been used such a laravel or codeigniter.

**Comment by wazowski78** [comment]
Please read #28
This is a base project of @yTakkar. He has told it some times, just go ahead and read other projects from him. I am not defending anyone, @yTakkar can show you more coding than websites. Can you program in Go, can you program in Switf or Objective-C, did you see this: 
https://github.com/yTakkar/React-Instagram-Clone-2.0 

Come on... be constructive. Don't troll over GitHub please. This issue is rubbish.
